StoreApp.Web/Models/Cart.cs
using System;
using StoreApp.Data.Concrete;
namespace StoreApp.Web.Models;

public class Cart
{
    public List<CartItem> Items { get; set; } = new List<CartItem>();

    public virtual void AddItem(Product product, int quntity)
    {
        var item = Items.Where(p => p.Product.Id == product.Id).FirstOrDefault();

        if (item == null)
        {
            Items.Add(new CartItem
            {
                Product = product,
                Quantity = quntity
            });
        }
        else
        {
            item.Quantity += quntity;
        }
    }

    public virtual void RemoveItem(Product product)
    {
        Items.RemoveAll(i => i.Product.Id == product.Id);
    }

    public decimal CalculateTotal()
    {
        return Items.Sum(i => i.Product.Price * i.Quantity);
    }

    public virtual void Clear()
    {
        Items.Clear();
    }

}

public class CartItem
{
    public int CartItemId { get; set; }
    public Product Product { get; set; } = new();
    public int Quantity { get; set; }
}

StoreApp.Web/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StoreApp.Data.Abstract;
using StoreApp.Data.Concrete;
using StoreApp.Web.Models;

namespace StoreApp.Web.Controllers;

public class OrderController : Controller
{
    private Cart cart;
    private IOrderRepository _orderRepository;
    public OrderController(Cart cartService, IOrderRepository orderRepository)
    {
        cart = cartService;
        _orderRepository = orderRepository;
    }

    public IActionResult Checkout()
    {
        return View(new OrderModel() { Cart = cart });
    }
    [HttpPost]
    public IActionResult Checkout(OrderModel model)
    {
        if (cart.Items.Count == 0)
        {
            ModelState.AddModelError("", "Sepetiniz der ürün bulunmamaktadır.");
        }
        if (ModelState.IsValid)
        {
            var order = new Order
            {
                Name = model.Name,
                Email = model.Email,
                City = model.City,
                Phone = model.Phone,
                AddressLine = model.AddressLine,
                OrderDate = DateTime.Now,
                OrderItems = cart.Items.Select(i => new OrderItem
                {
                    ProductId = i.Product.Id,
                    Price = (double)i.Product.Price,
                    Quantity = i.Quantity
                }).ToList()
            };
            _orderRepository.SaveOrder(order);
            cart.Clear();
            return RedirectToPage("/Completed", new { OrderId = order.Id });
        }
        else
        {
            model.Cart = cart;
            return View(model);
        }
    }


}

StoreApp.Web/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StoreApp.Data.Abstract;
using StoreApp.Web.Models;

namespace StoreApp.Web.Pages
{
    public class CartModel : PageModel
    {
        private IStoreRepository _repository;
        public CartModel(IStoreRepository repository, Cart cartService)
        {
            _repository = repository;
            Cart = cartService;
        }
        public Cart? Cart { get; set; }
        public void OnGet()
        {

        }

        public IActionResult OnPost(int id)
        {
            var product = _repository.Products.FirstOrDefault(i => i.Id == id);

            if (product != null)
            {
                Cart?.AddItem(product, 1);
            }

            return RedirectToPage("/cart");
        }

        public IActionResult OnPostRemove(int Id)
        {
            Cart?.RemoveItem(Cart.Items.First(p => p.Product.Id == Id).Product);
            return RedirectToPage("/cart");
        }
    }
}

StoreApp.Web/Pages/Cart.cshtml
@page
@model CartModel

<h2>Sepetim</h2>
@if(Model?.Cart?.Items.Count() == 0)
{
<div class="alert alert-warning">Sepetinizde Ürün yok</div>
}
else
{
        <table class="table table-bordered table striped">
            <thead>
                <tr>
                    <th>Quantity</th>
                    <th>İtem</th>
                    <th>Price</th>
                    <th>Total</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model?.Cart?.Items ?? Enumerable.Empty<CartItem>())
                    {
                    <tr>
                        <td>@item.Quantity</td>
                        <td>@item.Product.Name</td>
                        <td>@item.Product.Price TL</td>
                        <td>@((item.Quantity * item.Product.Price).ToString()) TL</td>
                        <td>
                            <form method="post" asp-page-handler="Remove">
                                <input type="hidden" name="Id" value="@item.Product.Id">
                                <button type="submit" class="btn bttn-sm btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                    }








            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3">Total :</td>
                    <td>
                        @Model?.Cart?.CalculateTotal() TL
                    </td>
                </tr>
            </tfoot>
        </table>
}


<div>
    <a href="/" class="btn btn-primary">Alışverişe Devam Et</a>
    <a class="btn btn-primary" asp-controller="Order" asp-action="Checkout">Siparişi Tamamla</a>
</div>

StoreApp.Web/Pages/Completed.cshtml
@page
<div class="text-center">
    <h2>Teşekkür Ederiz.</h2>
    <p>#@OrderId numaralı siparişiniz oluşturuldu.</p>
    <p>Siarpişiniz en kısa sürede teslim edilecektir</p>
    <a href="/" class="btn btn-primary">Ana Sayfa</a>
</div>

@functions {
    [BindProperty(SupportsGet = true)]
    public string? OrderId { get; set; }
}